# Add keybinds below
# (Add comments on what sections they're in?
# Shortcuts -> Crafting Log

"Crafting Log"   = "n"
# System -> Cycle through UI Component Tabs (Back
"Cycle Backward" = "["
# System -> Cycle through UI Component Tabs (Forward
"Cycle Forward"  = "]"
# System -> Confirm
"Confirm"        = "="

# For modifer combinations use + for SHIFT and ^ for CTRL
"Advanced Touch"        = "^3"
"Basic Synthesis"       = "^c"
"Basic Touch"           = "^6"
"Byregot's Blessing"    = "f"
"Byregot's Brow"        = "v"
"Byregot's Miracle"     = "^3"
"Careful Synthesis II"  = "1"
"Careful Synthesis III" = "2"
"Comfort Zone"          = "x"
"Focused Synthesis"     = "+v"
"Focused Touch"         = "+g"
"Great Strides"         = "e"
"Hasty Touch II"        = "4"
"Hasty Touch"           = "C"
"Ingenuity II"          = "q"
"Ingenuity"             = "+t"
"Initial Preparations"  = "+x"
"Inner Quiet"           = "c"
"Innovation"            = "r"
"Manipulation II"       = "t"
"Master's Mend II"      = "X"
"Master's Mend"         = "^g"
"Muscle Memory"         = "+c"
"Observe"               = "+z"
"Patient Touch"         = "^4"
"Piece by Piece"        = "+e"
"Precise Touch"         = "^5"
"Prudent Touch"         = "5"
"Rumination"            = "+r"
"Specialty: Reflect"    = "+f"
"Standard Synthesis"    = "^x"
"Standard Touch"        = "^s"
"Steady Hand II"        = "z"
"Tricks of the Trade"   = "g"
"Waste Not II"          = "^f"
